include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    invalid_use_of_protected_member: error
    missing_required_param: error
    missing_return: error
    dead_code: error

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_print: true
    always_use_package_imports: true
